name: Github Activity Readme Update

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 2 minutes"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_NAME: "Souleymane Sy"
          COMMIT_EMAIL: "souleymanesyservices@gmail.com"
          COMMIT_MSG: "docs(README): ⚡ update profile README with recent activity"
          EMPTY_COMMIT_MSG: "docs(README): 📝 empty commit to keep workflow active after 60 days of no activity"
          MAX_LINES: 10
