name: wakatime-stats-readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 5:00 am.

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "wakatime-readme-stats"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "docs(README): ⚡ updated wakatime readme stats metrics"
          COMMIT_USERNAME: "SouleymaneSy7"
          COMMIT_EMAIL: "souleymanesyservices@gmail.com"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 2
