name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: "0 12 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka-readme"
          COMMIT_MESSAGE: "config: updated waka-readme graph with new metrics"
          BLOCKS: "░▒▓█"
          TIME_RANGE: all_time
          CODE_LANG: typescript javascript rust
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
          IGNORED_LANGUAGES: YAML JSON TOML
          AUTHOR_NAME: "SouleymaneSy7"
          AUTHOR_EMAIL: "souleymanesyservices@gmail.com"
